function(register_os_macros target)
    if (UNIX)
        target_compile_definitions(${target} PRIVATE PA_OS_UNIX=1)
    endif ()
    if (WIN32)
        target_compile_definitions(${target} PRIVATE PA_OS_WINDOWS=1)
    endif ()
    if (CMAKE_SYSTEM_NAME STREQUAL "Android")
        target_compile_definitions(${target} PRIVATE PA_OS_ANDROID=1)
    endif ()
    if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(${target} PRIVATE PA_OS_LINUX=1)
    endif ()
endfunction()